using OGL.Common;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Xml.Serialization;

namespace OGL
{
    public class Language : IComparable<Language>, IXML, IOGLElement<Language>, IOGLElement
    {
        [XmlIgnore]
        public string FileName { get; set; }
        [XmlIgnore]
        public static XmlSerializer Serializer = new XmlSerializer(typeof(Language));
        public String Name { get; set; }
        public String Description { get; set; }
        public String Skript { get; set; }
        public String TypicalSpeakers { get; set; }
        public String Source { get; set; }
        [XmlIgnore]
        public bool ShowSource { get; set; } = false;

        public byte[] ImageData { get; set; }
        public void Register(OGLContext context, string file)
        {
            FileName = file;
            string full = Name + " " + ConfigManager.SourceSeperator + " " + Source;
            if (context.Languages.ContainsKey(full)) throw new Exception("Duplicate Language: " + full);
            context.Languages.Add(full, this);
            if (context.LanguagesSimple.ContainsKey(Name))
            {
                context.LanguagesSimple[Name].ShowSource = true;
                ShowSource = true;
            }
            else context.LanguagesSimple.Add(Name, this);
        }
        public Language() 
        {
            Skript = "";
            TypicalSpeakers = "";
        }
        public Language(OGLContext context, String name, String description, String skript, String speakers)
        {
            Name = name;
            Description = description;
            Skript = skript;
            TypicalSpeakers = speakers;
            Source = "Autogenerated";
            Register(context, null);
        }
        public String ToXML()
        {
            using (StringWriter mem = new StringWriter())
            {
                Serializer.Serialize(mem, this);
                return mem.ToString();
            }
        }
        public void Write(Stream stream)
        {
            Serializer.Serialize(stream, this);
        }
        public MemoryStream ToXMLStream()
        {
            MemoryStream mem = new MemoryStream();
            Serializer.Serialize(mem, this);
            return mem;
        }
        public override string ToString()
        {
            if (ShowSource || ConfigManager.AlwaysShowSource) return Name + " " + ConfigManager.SourceSeperator + " " + Source;
            return Name;
        }
        public int CompareTo(Language other)
        {
            return Name.CompareTo(other.Name);
        }
        public Language Clone()
        {
            using (MemoryStream mem = new MemoryStream())
            {
                Serializer.Serialize(mem, this);
                mem.Seek(0, SeekOrigin.Begin);
                Language r = (Language)Serializer.Deserialize(mem);
                r.FileName = FileName;
                return r;
            }
        }

        public bool Matches(string text, bool nameOnly)
        {
            CultureInfo Culture = CultureInfo.InvariantCulture;
            if (nameOnly) return Culture.CompareInfo.IndexOf(Name ?? "", text, CompareOptions.IgnoreCase) >= 0;
            return Culture.CompareInfo.IndexOf(Name ?? "", text, CompareOptions.IgnoreCase) >= 0
                || Culture.CompareInfo.IndexOf(Source ?? "", text, CompareOptions.IgnoreCase) >= 0
                || Culture.CompareInfo.IndexOf(Description ?? "", text, CompareOptions.IgnoreCase) >= 0
                || Culture.CompareInfo.IndexOf(Skript ?? "", text, CompareOptions.IgnoreCase) >= 0
                || Culture.CompareInfo.IndexOf(TypicalSpeakers ?? "", text, CompareOptions.IgnoreCase) >= 0;
        }
    }
}
